version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - "D:/Akshay/Mongo CRUD Operations/data:/home/jovyan/data"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - mongodb

volumes:
  mongo_data:
